// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxqxvdabwsbjgrcjluhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4cXh2ZGFid3NiamdyY2psdWhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MzQ2NDIsImV4cCI6MjA2NzExMDY0Mn0.cMabhjkBduRe_ifUi_EjN4ZiQpvFvNzm9XIoD8i69gk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});